### ISSUE TITLE
How to set key

### ISSUE THREAD

**Issue by internetxs** [clvLabs/PyATEMMax#10]
Hi maybe wrong way to ask but i am trying to find the correct command to set the key 1 to on
![image](https://user-images.githubusercontent.com/34030452/137464896-a06265b9-98e3-4d68-9a21-ba5a84345c39.png)
 
Could you tell me on how to do this?

Thanks

**Comment by florianschoffke** [comment]
@internetxs were you able to resolve this issue with the suggestion from @clvLabs?

I tried this and also tried to send my own cTTP message, but were still not able to set the key1 for next Transition. Is there another way to do it?
