### ISSUE TITLE
Setting macro name & notes

### ISSUE THREAD

**Issue by mitchellklijs** [clvLabs/PyATEMMax#15]
Hi, 

Is it possible to set a macro name & note when recording? As far as I can see, this is currently not implemented. In ATEM Software Control, this is implemented before starting recording. I would expect to see this functionality as parameters in `execMacroRecord`.

**Comment by clvLabs** [comment]
Hi again !

Checking the `MSRc` documentation for #14 I could see the fields are there, so it must be possible.
![MSRc](https://lh6.googleusercontent.com/HKOS_NUMuJjKSxYfLsS9EP7dhy7lCAmXj-66zrJ_W720JJt6b4OIbtp86e1lU6S7QiLHXE_sUUGEaksBAm4a5iWzRiWipPIkmRJN5-VFb5CtkxfPnxynO0iHY929iufIRaiPGXDR)

I'll start a new branch for this change and ask you (again) to test the change.

**Comment by clvLabs** [comment]
Fixed!

It will be available on the next version of the library :)

**Comment by clvLabs** [comment]
Version 1.0b8 already available.

**Comment by mitchellklijs** [comment]
Confirmed working for me as well!
