### ISSUE TITLE
execDownstreamKeyerAutoKeyer always affects dsk1 no matter which one is specified

### ISSUE THREAD

**Issue by nathanoday** [clvLabs/PyATEMMax#16]
My switcher variable is named atem1
I'm using execDownstreamKeyerAutoKeyer to turn on and off the downstream keyers using the auto transition, but no matter which keyer I specify, dsk1 is the one that gets turned on or off. My code looks like this:

`atem1.execDownstreamKeyerAutoKeyer(atem1.atem.dsks.dsk2)`

**Comment by 68040** [comment]
Which ATEM model do you use?
