### ISSUE TITLE
Set Key DVE Fill Source and Position

### ISSUE THREAD

**Issue by maanitm** [clvLabs/PyATEMMax#21]
How can you set the DVE Upstream Key, choose the two cameras, and set position. I am trying to build a Picture in Picture function using this library.

**Comment by clvLabs** [comment]
I don't know much about switchers, so my guess here can be wrong...

Reference: ["set" methods documentation](https://clvlabs.github.io/PyATEMMax/docs/methods/set/).

As far as I can see, there's only `downstream` methods in the library, I'm guessing the `DVE Upstream Key` you mention is what the library calls the `Keyer`, so you could try with the `setKeyerXXXX()` methods:

* `setKeyerBottom(mE:ATEMConstant, keyer:ATEMConstant, bottom:float)`
* `setKeyerFillSource(mE:ATEMConstant, keyer:ATEMConstant, fillSource:ATEMConstant)`
* `setKeyerFlyEnabled(mE:ATEMConstant, keyer:ATEMConstant, flyEnabled:bool)`
* `setKeyerFlyKeyFrame(mE:ATEMConstant, keyer:ATEMConstant, keyFrame:ATEMConstant)`
* `setKeyerKeySource(mE:ATEMConstant, keyer:ATEMConstant, keySource:ATEMConstant)`
* `setKeyerLeft(mE:ATEMConstant, keyer:ATEMConstant, left:float)`
* `setKeyerMasked(mE:ATEMConstant, keyer:ATEMConstant, masked:bool)`
* `setKeyerOnAirEnabled(mE:ATEMConstant, keyer:ATEMConstant, enabled:bool)`
* `setKeyerRight(mE:ATEMConstant, keyer:ATEMConstant, right:float)`
* `setKeyerTop(mE:ATEMConstant, keyer:ATEMConstant, top:float)`
* `setKeyerType(mE:ATEMConstant, keyer:ATEMConstant, type_:ATEMConstant)`

The related values can be read from `switcher.keyer[mE][keyer]` (see the [keyer section in switcher state docs](https://clvlabs.github.io/PyATEMMax/docs/data/state/#keyer)).

Please tell me if it helped so I can close the issue.
