### ISSUE TITLE
Can't select black as VideoSource

### ISSUE THREAD

**Issue by soulmark** [clvLabs/PyATEMMax#3]
Since switcher.atem.videoSources.black has a value of 0, the "if not foundSrc:" on line 234 of ATEMProtocol.py fails.
Changing to "if foundSrc == None:" fixes it.

Error traceback:
Traceback (most recent call last):
  File "mcmode_atem.py", line 130, in <module>
    0, switcher.atem.videoSources.black)
  File "/home/pi/.local/lib/python3.7/site-packages/PyATEMMax/ATEMSetterMethods.py", line 191, in setProgramInputVideoSource
    videoSource_val = self.atem.getVideoSrc(videoSource)
  File "/home/pi/.local/lib/python3.7/site-packages/PyATEMMax/ATEMProtocol.py", line 235, in getVideoSrc
    raise ATEMException(f"{source} ({type(source)}) is not a valid source")
PyATEMMax.ATEMException.ATEMException: black (<class 'PyATEMMax.ATEMConstant.ATEMConstant'>) is not a valid source

**Comment by clvLabs** [comment]
Thanks a lot !!!!  You are totally right.

At first sight, I see `getAudioSrc` is affected as well. I'll have a look to see if I can find anything else that could be affected by this bug and fix them all at once.

**Comment by clvLabs** [comment]
v1.0b3 available on https://pypi.org/project/PyATEMMax/
