### ISSUE TITLE
Detect when the PVW/PGM has changed

### ISSUE THREAD

**Issue by oli-tolnai** [clvLabs/PyATEMMax#33]
Is it possible to see if the PVW or the PGM has changed? Maybe when the PVW has changed from another software (e.g. someone using the Atem Software Control), then my program detects it, and print that which camera is on PVW?

**Comment by clvLabs** [comment]
Have a look at [the tally-str example](https://clvlabs.github.io/PyATEMMax/docs/examples/tally-str/), I think it's just what you need.

Please confirm if I can close the issue with this.

**Comment by oli-tolnai** [comment]
Thank You! That's what I was looking for.
