### ISSUE TITLE
Live streaming 

### ISSUE THREAD

**Issue by Rameshkannan1988** [clvLabs/PyATEMMax#7]
Dear sir, I need to live streaming the video to YouTube using this library but I  could not find the streaming class in this library. Please help to find out the solution

**Comment by clvLabs** [comment]
Dear Ramesh,

I'm afraid the BlackMagic protocol used by PyATEMMax has no streaming capabilities.
As the protocol itself is not open sourced, we have no insights about the last version and if this feature is available in the newer versions it won't be available in PyATEMMax (as long as BlackMagic doesn't open the protocol) - see https://clvlabs.github.io/PyATEMMax/about/atem-version/

Good luck with your project ! If you find a way to reach your goal I would greatly appreciate it if you send me some info   :)

**Comment by 68040** [comment]
@Rameshkannan1988
When your ATEM device has streaming support (like the Mini Pro and Extreme), you're able to start and stop streaming and recording. Just connect to port 9993 via telnet or netcat.
To start streaming send `stream start: url: youtube-url key: secretkey bitrate: 9000000`
For stop streaming send `stream stop`
To get a list of available command send a `?`
